@url = http://localhost:8080/api/appuser

###

POST {{url}}/create/ HTTP/1.1
Content-Type: application/json
Accept: application/json

{ 
  "userName": "userName123",
 "password": "password1!"
 }


###




