@url = http://localhost:8080/api/game

###
GET {{url}}/user/130db43f-418c-11ec-8708-0242ac110002 HTTP/1.1
Accept: application/json

###

POST {{url}} HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "gameId": 0,
  "timeElapsed": 0,
  "playerTurn": 1,
  "countryList": [{
  "gameId": 0,
  "countryId": 0,
  "playerPossession": 0,
  "army": 1
}, {
  "gameId": 0,
  "countryId": 1,
  "playerPossession": 0,
  "army": 1
},{
  "gameId": 0,
  "countryId": 2,
  "playerPossession": 0,
  "army": 1
},{
  "gameId": 0,
  "countryId": 3,
  "playerPossession": 0,
  "army": 1
},{
  "gameId": 0,
  "countryId": 4,
  "playerPossession": 0,
  "army": 1
},{
  "gameId": 0,
  "countryId": 5,
  "playerPossession": 0,
  "army": 1
},{
  "gameId": 0,
  "countryId": 6,
  "playerPossession": 0,
  "army": 1
},{
  "gameId": 0,
  "countryId": 7,
  "playerPossession": 0,
  "army": 1
},{
  "gameId": 0,
  "countryId": 8,
  "playerPossession": 0,
  "army": 1
},{
  "gameId": 0,
  "countryId": 9,
  "playerPossession": 0,
  "army": 1
},{
  "gameId": 0,
  "countryId": 10,
  "playerPossession": 0,
  "army": 1
},{
  "gameId": 0,
  "countryId": 11,
  "playerPossession": 0,
  "army": 1
},{
  "gameId": 0,
  "countryId": 12,
  "playerPossession": 0,
  "army": 1
},{
  "gameId": 0,
  "countryId": 13,
  "playerPossession": 0,
  "army": 1
},{
  "gameId": 0,
  "countryId": 14,
  "playerPossession": 0,
  "army": 1
},{
  "gameId": 0,
  "countryId": 15,
  "playerPossession": 0,
  "army": 1
},{
  "gameId": 0,
  "countryId": 16,
  "playerPossession": 0,
  "army": 1
},{
  "gameId": 0,
  "countryId": 17,
  "playerPossession": 0,
  "army": 1
},{
  "gameId": 0,
  "countryId": 18,
  "playerPossession": 0,
  "army": 1
},{
  "gameId": 0,
  "countryId": 19,
  "playerPossession": 0,
  "army": 1
},{
  "gameId": 0,
  "countryId": 20,
  "playerPossession": 0,
  "army": 1
},{
  "gameId": 0,
  "countryId": 21,
  "playerPossession": 0,
  "army": 1
},{
  "gameId": 0,
  "countryId": 22,
  "playerPossession": 0,
  "army": 1
},{
  "gameId": 0,
  "countryId": 23,
  "playerPossession": 0,
  "army": 1
},{
  "gameId": 0,
  "countryId": 24,
  "playerPossession": 0,
  "army": 1
},{
  "gameId": 0,
  "countryId": 25,
  "playerPossession": 0,
  "army": 1
},{
  "gameId": 0,
  "countryId": 26,
  "playerPossession": 0,
  "army": 1
},{
  "gameId": 0,
  "countryId": 27,
  "playerPossession": 0,
  "army": 1
},{
  "gameId": 0,
  "countryId": 28,
  "playerPossession": 0,
  "army": 1
},{
  "gameId": 0,
  "countryId": 29,
  "playerPossession": 0,
  "army": 1
},{
  "gameId": 0,
  "countryId": 30,
  "playerPossession": 0,
  "army": 1
},{
  "gameId": 0,
  "countryId": 31,
  "playerPossession": 0,
  "army": 1
},{
  "gameId": 0,
  "countryId": 32,
  "playerPossession": 0,
  "army": 1
},{
  "gameId": 0,
  "countryId": 33,
  "playerPossession": 0,
  "army": 1
},{
  "gameId": 0,
  "countryId": 34,
  "playerPossession": 0,
  "army": 1
},{
  "gameId": 0,
  "countryId": 35,
  "playerPossession": 1,
  "army": 1
},{
  "gameId": 0,
  "countryId": 36,
  "playerPossession": 0,
  "army": 1
},{
  "gameId": 0,
  "countryId": 37,
  "playerPossession": 0,
  "army": 1
},{
  "gameId": 0,
  "countryId": 38,
  "playerPossession": 0,
  "army": 1
},{
  "gameId": 0,
  "countryId": 39,
  "playerPossession": 0,
  "army": 1
},{
  "gameId": 0,
  "countryId": 40,
  "playerPossession": 0,
  "army": 1
},{
  "gameId": 0,
  "countryId": 41,
  "playerPossession": 0,
  "army": 1
}],
"players": [
{"gameId": 0,
"userId": "130db43f-418c-11ec-8708-0242ac110002",
"turnOrder": 0},
{"gameId": 0,
"userId": null,
"turnOrder": 1},
{"gameId": 0,
"userId": null,
"turnOrder": 2}
]
}

###

POST {{url}} HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "gameId": 4,
  "timeElapsed": 0,
  "playerTurn": 1
}


###

PUT {{url}}/4 HTTP/1.1
Content-Type: application/json

{
  "gameId": 4,
  "timeElapsed": 0,
  "playerTurn": 2
}

###

DELETE {{url}}/4 HTTP/1.1

###

#{
#  "gameId": 0,
#  "timeElapsed": 0,
#  "playerTurn": 2,
#  "countryList": [{ "gameId": 0,  "countryId": 0,  "playerPossession": 0,  "army": 1},{ "gameId": 0,  "countryId": 2, "playerPossession": 0,  "army": 1}, etc.]
#  "players" {"gameId": 0,"userId": "4d980627-3b3c-11ec-8708-0242ac110002","turnOrder": 0},{"gameId": 0,"userId": null,"turnOrder": 1},{"gameId": 0,"userId": null,"turnOrder": 2}
#}

###
POST {{url}} HTTP/1.1


